### ISSUE TITLE
Error in line 21, in <module> from txt2img2img.dependencies import shortcodes

### ISSUE THREAD

**Issue by Pharonix** [ThereforeGames/txt2img2img#12]
When running the StableDiffusion batch file, it throws an error that txt2img2img cannot be loaded

Traceback (most recent call last):
  File "C:\Users\user\Documents\WaifuDif\stable-diffusion-webui\modules\scripts.py", line 71, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\Users\user\Documents\WaifuDif\stable-diffusion-webui\scripts\txt2img2img.py", line 21, in <module>
    from txt2img2img.dependencies import shortcodes
ModuleNotFoundError: No module named 'txt2img2img'

Line 21:
from txt2img2img.dependencies import shortcodes

**Comment by Pharonix** [comment]
Ok, I see.

The link from the stable diffusion "custom scripts" page, only linked to the main script, and not the main page that has all the info
