### ISSUE TITLE
Rembg installation in venv completely breaks AUTOMATIC's webui

### ISSUE THREAD

**Issue by DenkingOfficial** [ThereforeGames/txt2img2img#4]
When I'm trying to start the webui after installing rembg to venv an error occures
I think there is a conflict between webui requirements and rembg requirements

Log when I'm trying to start webui-user.bat:

```
Installing collected packages: Pillow, numpy, scikit-image
  Attempting uninstall: Pillow
    Found existing installation: Pillow 9.0.1
    Uninstalling Pillow-9.0.1:
      Successfully uninstalled Pillow-9.0.1

stderr: ERROR: Could not install packages due to an OSError: [WinError 5]   : 'C:\\Software\\Other Software\\sdautomatic111\\venv\\Lib\\site-packages\\~il\\_imaging.cp39-win_amd64.pyd'
Check the permissions.
```

**Comment by ThereforeGames** [comment]
Hi, I haven't seen this problem before - what method of installation did you use? If pip, have you tried running the command again with the --user flag to avoid issues with permissions?

**Comment by DenkingOfficial** [comment]
I installed rembg to venv using

`pip install rembg[gpu]`

After that I started webui-user.bat, it checked for all of dependencies and throwed and error

UPD: Found another error in logs:

```
Installing requirements for Web UI
Traceback (most recent call last):
  File "C:\Software\Other Software\sdautomatic111\launch.py", line 116, in <module>
    run_pip(f"install -r {requirements_file}", "requirements for Web UI")
  File "C:\Software\Other Software\sdautomatic111\launch.py", line 54, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "C:\Software\Other Software\sdautomatic111\launch.py", line 44, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Web UI.
Command: "C:\Software\Other Software\sdautomatic111\venv\Scripts\python.exe" -m pip install -r requirements_versions.txt --prefer-binary
Error code: 1
```

**Comment by DenkingOfficial** [comment]
> Hi, I haven't seen this problem before - what method of installation did you use? If pip, have you tried running the command again with the --user flag to avoid issues with permissions?

I can't use `--user` in venv. It throws me this error:
`Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`

So I still can't figure out how to install rembg into AUTOMATIC1111s venv properly.
rembg installed some other versions of the packages and I think there is a conflict between them
